# Generated by Django 5.2.8 on 2025-11-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
    ]
